//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBuy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aircraft()
        {
            this.ScheduledRoute = new HashSet<ScheduledRoute>();
            this.Seat = new HashSet<Seat>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int type_id { get; set; }
        public int airline_id { get; set; }
        public int operator_id { get; set; }
        public int seat_capacity { get; set; }
        public int lines_count { get; set; }
        public int business_line { get; set; }
        public int premium_line { get; set; }
    
        public virtual AircraftType AircraftType { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual Airline Airline1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledRoute> ScheduledRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seat { get; set; }
    }
}
