//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBuy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightEntities : DbContext
    {
        public FlightEntities()
            : base("name=FlightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<AircraftType> AircraftType { get; set; }
        public virtual DbSet<Airline> Airline { get; set; }
        public virtual DbSet<AirlineCode> AirlineCode { get; set; }
        public virtual DbSet<Airport> Airport { get; set; }
        public virtual DbSet<AirportCode> AirportCode { get; set; }
        public virtual DbSet<Baggage> Baggage { get; set; }
        public virtual DbSet<BaggageClass> BaggageClass { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CodeType> CodeType { get; set; }
        public virtual DbSet<FullRoute> FullRoute { get; set; }
        public virtual DbSet<FullRouteRoutes> FullRouteRoutes { get; set; }
        public virtual DbSet<Gate> Gate { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<ScheduledRoute> ScheduledRoute { get; set; }
        public virtual DbSet<ScheduledRouteStatus> ScheduledRouteStatus { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<SeatClass> SeatClass { get; set; }
        public virtual DbSet<SeatRow> SeatRow { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<SeatClassDiscounts> SeatClassDiscounts { get; set; }
    }
}
