//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBuy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FullRoute()
        {
            this.FullRouteRoutes = new HashSet<FullRouteRoutes>();
            this.FullRouteRoutes1 = new HashSet<FullRouteRoutes>();
        }
    
        public int id { get; set; }
        public int airline_id { get; set; }
    
        public virtual Airline Airline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullRouteRoutes> FullRouteRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullRouteRoutes> FullRouteRoutes1 { get; set; }
    }
}
