//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBuy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledRoute()
        {
            this.FullRouteRoutes = new HashSet<FullRouteRoutes>();
            this.Ticket = new HashSet<Ticket>();
            this.Gate = new HashSet<Gate>();
            this.Terminal = new HashSet<Terminal>();
            this.FullRouteRoutes1 = new HashSet<FullRouteRoutes>();
        }
    
        public int id { get; set; }
        public int route_id { get; set; }
        public int aircraft_id { get; set; }
        public Nullable<System.DateTime> scheduled_departure_datetime { get; set; }
        public Nullable<System.DateTime> actual_departure_datetime { get; set; }
        public Nullable<System.DateTime> scheduled_arrival_datetime { get; set; }
        public Nullable<System.DateTime> actual_arrival_datetime { get; set; }
        public Nullable<System.TimeSpan> registration_time { get; set; }
        public Nullable<System.TimeSpan> board_time { get; set; }
        public int status_id { get; set; }
        public decimal base_cost { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullRouteRoutes> FullRouteRoutes { get; set; }
        public virtual Route Route { get; set; }
        public virtual ScheduledRouteStatus ScheduledRouteStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gate> Gate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terminal> Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FullRouteRoutes> FullRouteRoutes1 { get; set; }
    }
}
