//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBuy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Baggage = new HashSet<Baggage>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public int seat_id { get; set; }
        public int scheduled_route_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ScheduledRoute ScheduledRoute { get; set; }
        public virtual Seat Seat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Baggage> Baggage { get; set; }
    }
}
